# Define UI for app that draws a histogram ----
source('dependencies.R')
source('config.R')

ui <- navbarPage(title = appName,
                 tabPanel('Main',
                          wellPanel(
                            uiOutput('manualRefreshUI'),
                            fluidRow(
                              column(3,
                                     uiOutput('chooseScaleUI')
                                     ),
                              column(3,
                                     uiOutput('chooseMetricUI')
                                     ),
                              column(2,
                                     uiOutput('chooseDiffUI')
                                    ),
                              column(2,
                                     uiOutput('chooseSmoothUI')
                              ),
                              column(2,
                                     uiOutput('chooseNormaliseUI')
                              )
                            ),
                            uiOutput('chooseCountryUI'),
                            fluidRow(
                              column(6,
                                     plotlyOutput('doPlotUI'),
                              ),
                              column(6,
                                     plotlyOutput('allPlotsUI')
                              )
                            ),
                            uiOutput('showPlotInfoUI')
                          ),
                          
    
                          ),
                 tabPanel(
                   'Maps',
                   wellPanel(
                     fluidRow(
                       column(4,
                              uiOutput('dayMapUI')
                       ),
                       column(4,
                              uiOutput('plotTypeUI')
                       ),
                       column(4,
                              uiOutput('plotMetricUI')
                              )
                     ),
                     uiOutput('countryMapUI'),
                     uiOutput('mapTitleUI'),
                     plotOutput('mapUI'),
                     uiOutput('markdownMapUI')
                   )
                 ),
                 tabPanel('Help',
                         includeMarkdown('vignettes/help.md'))
)