# Define UI for app that draws a histogram ----
library('shinythemes')
library('dplyr')
library('tidyr')
library('ggplot2')
library('here')
library('markdown')
library('zoo')
library('rnaturalearth')
library('rnaturalearthdata')
library('countrycode')
library('rgeos')

ui <- navbarPage(title = 'COVID 19 Tracker',
                 #theme = shinytheme('united'),
                 tabPanel('Main',
                          wellPanel(
                            fluidRow(
                              column(4,
                                     uiOutput('chooseScaleUI')
                                     ),
                              column(4,
                                     uiOutput('chooseMetricUI')
                                     ),
                              column(4,
                                     uiOutput('chooseDiffUI')
                              )
                            ),
                            uiOutput('chooseCountryUI'),
                            fluidRow(
                              column(6,
                                     plotOutput('doPlotUI'),
                                     fluidRow(
                                      column(6,
                                             uiOutput('chooseAlignUI')
                                             ), 
                                      column(6,
                                             uiOutput('choosePlotLimUI')
                                             )
                                     )
                              ),
                              column(6,
                                     plotOutput('allPlotsUI')
                              )
                            )
                          ),
                          
    
                          ),
                 tabPanel(
                   'Map',
                   wellPanel(
                     fluidRow(
                       column(2,
                              uiOutput('logicalCountryMapUI'),
                              uiOutput('logicalRemoveCountryMapUI')
                       ),
                       column(6,
                              uiOutput('dayMapUI')
                       ),
                       column(2,
                              uiOutput('normalizeMapUI')
                              ),
                       column(2,
                              uiOutput('trendMapUI')
                       )
                     ),
                     uiOutput('countryMapUI'),
                     uiOutput('removeCountryMapUI'),
                     plotOutput('mapUI'),
                     uiOutput('mapQChoiceUI'),
                     plotOutput('mapQUI')
                   )
                 ),
                 tabPanel('Background',
                         includeMarkdown('vignettes/background.md')),
                 tabPanel('Coming next',
                         includeMarkdown('vignettes/coming.md')),
                 tabPanel('About',
                         includeMarkdown('vignettes/about.md'))
)